import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { createJetpackModel } from '../../src/rooms/jetpackModel.mjs';

const renderer = new THREE.WebGLRenderer({ canvas: document.querySelector('canvas'), antialias: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.25;
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
const scene = new THREE.Scene();
scene.background = new THREE.Color(0x14262b);
scene.fog = new THREE.Fog(0x14262b, 5, 12);
const camera = new THREE.PerspectiveCamera(33, innerWidth / innerHeight, .01, 30);
camera.position.set(1.45, 1.1, 2.5);
const controls = new OrbitControls(camera, renderer.domElement);
controls.target.set(0, .49, 0);
controls.enableDamping = true;
controls.autoRotate = true;
controls.autoRotateSpeed = .75;
controls.minDistance = 1.5;
controls.maxDistance = 5;
controls.maxPolarAngle = Math.PI * .55;
scene.add(new THREE.HemisphereLight(0xccebe6, 0x273134, 2.2));
const key = new THREE.DirectionalLight(0xffddaa, 3.8);
key.position.set(-2, 3, 4);
key.castShadow = true;
key.shadow.mapSize.set(1024, 1024);
key.shadow.camera.left = key.shadow.camera.bottom = -2;
key.shadow.camera.right = key.shadow.camera.top = 2;
key.shadow.normalBias = .01;
scene.add(key);
const rim = new THREE.DirectionalLight(0x91ffed, 3.5);
rim.position.set(2, 1.5, -3);
scene.add(rim);
const { root, update } = createJetpackModel();
root.position.y = .18;
scene.add(root);
const floor = new THREE.Mesh(new THREE.PlaneGeometry(200, 200), new THREE.MeshStandardMaterial({ color: 0x183239, roughness: .88 }));
floor.rotation.x = -Math.PI / 2;
floor.position.y = -.18;
floor.receiveShadow = true;
scene.add(floor);
const plinth = new THREE.Mesh(new THREE.CylinderGeometry(.62, .69, .06, 64), new THREE.MeshStandardMaterial({ color: 0x345259, roughness: .7, metalness: .2 }));
plinth.position.y = -.13;
plinth.receiveShadow = true;
scene.add(plinth);
let enabled = false;
const button = document.querySelector('#activation');
button.addEventListener('click', () => {
  enabled = !enabled;
  button.setAttribute('aria-pressed', String(enabled));
  button.textContent = enabled ? 'Spegni i propulsori' : 'Accendi i propulsori';
});
function resize() {
  renderer.setSize(innerWidth, innerHeight);
  camera.aspect = innerWidth / innerHeight;
  camera.updateProjectionMatrix();
}
addEventListener('resize', resize);
resize();
renderer.setAnimationLoop(milliseconds => {
  const time = milliseconds * .001;
  root.position.y = enabled ? .34 + Math.sin(time * 2.1) * .025 : .18 + Math.sin(time * 1.4) * .014;
  update(time, { enabled, thrusting: enabled });
  controls.update();
  renderer.render(scene, camera);
});
